spring:
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:lybgeek}
    database: 0
    timeout: 10000
    # redis 集群
#    cluster:
#      nodes: ${REDIS_NODES:10.1.4.71:7001,10.1.4.71:7002,10.1.4.71:7003,10.1.4.71:7004,10.1.4.71:7005,10.1.4.71:7006}
#    password: ${REDIS_PASSWORD:123456}
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 500
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1

